### ISSUE TITLE
Feature Request: Bumps and Number Stations

### ISSUE THREAD

**Issue by DonaldTsang** [cburmeister/radio#2]
- [ ] Voice Overs and/or Bumps 
    - [ ] Every n minutes (timed)
    - [ ] Every n songs (count)
- [ ] Number Station (preset playlist)
    - [ ] Plays every n days at a certain time
    - [ ] Plays in random times of the day

**Comment by cburmeister** [comment]
Hello,

All of these features are already supported -- see the `liquidsoap` documentation here:

https://www.liquidsoap.info/doc-1.3.4/documentation.html

**Comment by DonaldTsang** [comment]
@cburmeister could you guide me through some of the documentation?
